---

 - hosts: localhost
   name: install synfony app
   become_user: root
   
   tasks:
     - name: install tasks dependesies
       become: yes 
       apt:
         pkg:
           - gpg
           - python3-apt

     - name: add synfony-cli apt repo
       become: yes
       ansible.builtin.apt_repository:
         repo: deb [trusted=yes] https://repo.symfony.com/apt/ /
         state: present
         filename: symfony-cli

     - name: install synfony-cli
       become: yes
       apt: 
         name: symfony-cli
         state: latest
         update_cache: yes
     
     - name: install docker repo key
       become: yes
       apt_key:
         url: https://download.docker.com/linux/ubuntu/gpg
         state: present
         keyring: /usr/share/keyrings/docker-archive-keyring.gpg

     - name: add docker apt repo
       become: yes
       ansible.builtin.apt_repository:
         repo: deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu   impish stable
         state: present

     - name: install docker
       become: yes
       apt:
         pkg: 
           - docker-ce
           - docker-ce-cli
           - containerd.io
         state: latest
         update_cache: yes

     - name: install docker-compose from website
       become: yes
       get_url: 
         url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
         dest: /usr/local/bin/docker-compose
         owner: root
         group: root
         mode: "u=rwx,g=rx,o=rx"

     - name: install php ppa repo
       become: yes
       apt_repository:
         repo: ppa:ondrej/php
         state: present

     - name: install php8 and plugins (xml & apcu)
       become: yes
       apt:
         pkg: 
           - php8.0
           - php8.0-xml
           - php8.0-apcu
           - php8.0-pgsql # PostgreSQL
         state: latest

     - name: add sourceCode group
       become: yes
       ansible.builtin.group:
         name: sourceCode
         state: present

     - name: create project user (symfony)
       become: yes
       ansible.builtin.user:
         name: symfony
         shell: /bin/bash
         groups: docker,sourceCode
         append: yes

     - name: create code dir
       become: yes
       file: 
          path: /usr/local/src/onehelth
          mode: u=rwx,g=rwx,o=
          owner: symfony
          group: sourceCode
          state: directory

     - name: get code from github
       become: yes
       become_user: symfony
       git:
         repo: https://github.com/Droppy01/onehelth
         dest: /usr/local/src/onehelth

     - name: install composer plugins via symfony-cli
       become: yes
       become_user: symfony
       ansible.builtin.command: symfony composer install
       args:
         chdir:  /usr/local/src/onehelth/

     - name: create docker service file
       become: yes
       copy:
         content: |
           [Unit]
           Description=docker symfony project
           Requires=docker.service
           After=docker.service

           [Service]
           User=symfony
           ExecStart=/usr/local/bin/docker-compose --project-directory /usr/local/src/onehelth/ up
           
           [Install]
           WantedBy=multi-user.target
         dest: /etc/systemd/system/docker-symfony-server.service
         owner: root
         group: root
         mode: u=rw,g=rw,o=r

     - name: create service file symfony
       become: yes
       copy:
         content: |
           [Unit]
           Description=serve symfony project
           Requires=docker-symfony-server.service
           After=docker-symfony-server.service

           [Service]
           User=symfony
           ExecStart=/usr/bin/symfony local:server:start --dir=/usr/local/src/onehelth/
           
           [Install]
           WantedBy=multi-user.target
         dest: /etc/systemd/system/symfony-server.service
         owner: root
         group: root
         mode: u=rw,g=rw,o=r

     - name: reload systemd
       become: yes
       command: systemctl daemon-reload
                 

